name: PNPM Build on Push
on:
  push:
    branches: ['main']

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # 第一步：先安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      # 第二步：再配置 Node.js，并启用 pnpm 缓存（此时 pnpm 已存在）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm' # 现在能找到 pnpm，正常解析缓存

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build command
        run: pnpm run build:weapp:preview
